### ISSUE TITLE
PUSHER eror 400 

### ISSUE THREAD

**Issue by Jieyab89** [mydnic/kanpen#37] opened 2021-02-27 08:42 UTC
Hallo, nice package 

I have eror, cant input email in form, and notice eror pusher 400. How to fix it ? 

Thank You

**Comment by mydnic** [comment] 2021-02-28 20:32
I don't have any issue ? If maybe you have a repo where I can reproduce, it would help.
Maybe you have a middleware issue ?
I'm closing for the moment but don't hesitate to reply with more info

**Closed as completed by mydnic** 2021-02-28 20:32 UTC

**Comment by Jieyab89** [comment] 2021-10-06 06:17
![image](https://user-images.githubusercontent.com/71226310/136150191-55ffc98a-eae9-40c3-bed4-f406e149c876.png)
Hello mydnic

Sorry I just replied, I just had time to open my account. I have a problem when a user enters an email address it will display a pusher 400 error then where is the error?

In the past when I used your pacakge it worked but over time there was an error in the pusher

There is table subscribers 

![image](https://user-images.githubusercontent.com/71226310/136150423-6f020a12-5eee-465f-8f53-b95d05e9263c.png)

**Comment by mydnic** [comment] 2021-10-13 09:02
Are you listening for Events ? 

The issue comes from your project I think because this package does not trigger any listener and does not broadcast anything with pusher

**Comment by Jieyab89** [comment] 2021-10-15 19:04
Yeah i;m use laravel event. I've tried composer update. But this way doesn't work, if I give code access to fix it what should I show my code? Maybe I need your help, if you like later I will create a private repo and provide the code you need

Thanks, success for you
